numpy einstein summation tricks:

In [3]:
import numpy as np

Outer product:

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])
command = 'i,i->i'
print('----\n', a, '\nand\n', b)
print(f'two lists of shape (i,) => {np.einsum(command, a, b)}')

----
 [1 2 3] 
and
 [4 5 6]
two lists of shape (i,) => [ 4 10 18]


In [5]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
command = 'ij,ij->ij'
print('----\n', a, '\nand\n', b)
print(f'two lists of shape (1,i) => {np.einsum(command, a, b)}')

----
 [[1 2 3]] 
and
 [[4 5 6]]
two lists of shape (1,i) => [[ 4 10 18]]


In [6]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]]).T
command = 'ij,ji->ij'   # swapped ij to ji
print('----\n', a, '\nand\n', b)
print(f'two lists of shape (1,i) and (i,1) => {np.einsum(command, a,b)}')

----
 [[1 2 3]] 
and
 [[4]
 [5]
 [6]]
two lists of shape (1,i) and (i,1) => [[ 4 10 18]]
