simple example on how to extract patterns in matrices

in this example can find horizontal, vertical or diagonal patterns for match (5) game

In [1]:
import numpy as np
np.random.seed(0)
from scipy import signal
arr = np.random.randint(0,2, size = (6,6))
print(arr,'\n')

[[0 1 1 0 1 1]
 [1 1 1 1 1 0]
 [0 1 0 0 0 0]
 [0 1 0 1 1 0]
 [0 1 1 1 1 0]
 [1 0 1 0 1 1]] 



In [2]:
diag_kern = np.eye(3)

print(diag_kern,'\n')

corr_diag = signal.correlate(arr, diag_kern/np.sum(diag_kern), mode='same').astype(float)
print(np.int8(corr_diag == 1))

diag_kern = np.fliplr(np.eye(3))
print(diag_kern,'\n')
corr_diag = signal.correlate(arr, diag_kern/np.sum(diag_kern), mode='same').astype(float)
print(np.int8(corr_diag == 1))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]] 

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 0]]


In [3]:
horiz_kern= np.zeros((3,3))
horiz_kern[1,...] = 1
print(horiz_kern,'\n')
corr_diag = signal.correlate(arr, horiz_kern/np.sum(horiz_kern), mode='same').astype(float)
print(np.int8(corr_diag == 1))


vert_kern = horiz_kern.T
print(vert_kern,'\n')
corr_diag = signal.correlate(arr, vert_kern/np.sum(vert_kern), mode='same').astype(float)
print(np.int8(corr_diag == 1))

[[0. 0. 0.]
 [1. 1. 1.]
 [0. 0. 0.]] 

[[0 0 0 0 0 0]
 [0 1 1 1 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 1 0 0]
 [0 0 0 0 0 0]]
[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]] 

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]


meme method. for education. disregard

In [5]:
import numpy as np
arr = np.array([0,1,1,0,1,0,1,1])
n_arr = len(arr)
print('index-value\n', np.vstack((np.arange(n_arr),arr)))
mask = np.array([1,1])

n_mask = len(mask)
n_steps = n_arr - n_mask + 1

match = np.zeros(n_steps, dtype = bool)

# start examining slices or arr of size 2 # and comparing
# i.e. if [0,1] == [1,1] -> [False, True]
# np.all([False, True]) = False; np.all([True, True]) = True
for i in range(n_steps):
    slice = arr[i:i+n_mask]
    if np.all(slice == mask):   
        match[i] = True         

where_match_starts = np.argwhere(match == True)

for start in where_match_starts:
    print('pattern ', mask,'matches from ', start, 'to', start + n_mask - 1)

index-value
 [[0 1 2 3 4 5 6 7]
 [0 1 1 0 1 0 1 1]]
pattern  [1 1] matches from  [1] to [2]
pattern  [1 1] matches from  [6] to [7]


In [6]:
ijs = []
dim_i = 3
dim_j = 3
for i in range(dim_i):
    ijs.append([])
    for j in range(dim_j):
        ijs[-1].append(str(i)+str(j))
        
a = np.array(ijs)
print(a)
slc = np.arange(len(a))
print(a[slc,slc])

[['00' '01' '02']
 ['10' '11' '12']
 ['20' '21' '22']]
['00' '11' '22']
