In [8]:
import cv2, numpy as np
import matplotlib.pyplot as plt
k_shape = (5,5)
ker_rct = cv2.getStructuringElement(cv2.MORPH_RECT      ,k_shape)
ker_ell = cv2.getStructuringElement(cv2.MORPH_ELLIPSE   ,k_shape)
ker_crs = cv2.getStructuringElement(cv2.MORPH_CROSS     ,k_shape)
print(ker_rct,ker_ell,ker_crs, sep='\n\n')

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

[[0 0 1 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 0 1 0 0]]

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
